version: '3.9'

services:
  app:
    build: ./app
    volumes:
      - ./app:/code/app
    ports:
      - 5001:5000
    env_file:
      - ./.env
    depends_on: 
      db:
        condition: service_healthy
    links: 
      - db
    networks:
     - ntwrk
  db:
    image: mariadb
    ports:
      - 3306:3306
    env_file:
      - ./.env
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/sql:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
     - ntwrk
    healthcheck:
      test: "/usr/bin/mysql --user=${MARIADB_USER} --password=${MARIADB_PASSWORD} --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 1s
      retries: 5

networks:
  ntwrk:
    driver: bridge
